version: '2'

services:
  proxy:
    image: nginx
    volumes:
      - $PWD/public:/usr/share/nginx/html:ro
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    image: node
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
    command: "npm run dev"

